frames = {
  "1024": "What is a better way for making voting mandatory for younger generation?",
  "1025": "What is a stronger driver of youth voter turnout: particular candidates or particular issues? And how can we use that to increase youth voter turnout?",
  "1026": "What do young people think about the government?",
  "1027": "How strong is the knowledge of young people about the differences between political parties?",
  "1028": "To what extent are young people aware of the process of voting?",
  "1029": "How can we increase youth voters turnout through the role of school?",
  "1030": "How might we encourage students to go vote during the school year?",
  "1031": "What are our schools teaching young people about the importance of voting?",
  "1032": "How might we convince employed young people to vote? ",
  "1033": "What are the pros and cons of voting to a young adult?",
  "1034": "Why youth don't vote? Does a youth community help to encourage more votes?",
  "1035": "What are ways that voting is currently unaccessible to young voters, and how can we reduce these barriers?",
  "1036": "Is there a way to lower costs (not monetary costs) of voting for younger generations?",
  "1037": "How can we sponsor youth participation in government processes?",
  "1038": "Are young people more inclined to vote if voting was only done online?",
  "1039": "How can we incentivize the younger generation to vote?",
  "1040": "What motivates young adults to attend an event in person?",
  "1001": "How can we enable engaged individuals to convince younger, unengaged voters that voting is important?", 
  "1002": "How would you encourage the younger generation to feel an obligation to vote?",
  "1003": "How might we help young, eligible, and motivated voters learn how to become engaged in the political process?",
  "1004": "How might we convince employed young people to vote?",
  "1005": "How can we get older folks and/or younger folks who know how to work the system to \"apprentice\" young eligible voters who are motivated but not yet engaged?",
  "1006": "What elements of social psychology inform the outlook young people have on voting?",
  "1007": "How can we sponsor youth participation in government processes?",
  "1008": "Based on current states in there a correlation between parents education/interest and youth votes?",
  "1009": "How does first-generation parents not participating in voting affect their second-generation children in voting?",
  "1010": "How might we increase youth voter turnout through the impact of the parents onto their children?",
  "1011": "What is the role of media in increasing youth vote?",
  "1012": "How does the government market young adults to vote?",
  "1013": "How should we use the internet to motivate younger generation to vote?",
  "1014": "How might social media help with increasing voters turnout? ",
  "1015": "How can we empower youth to contribute to political efforts that are relevant to their interests?",
  "1016": "How do the voting habits of young people reflect the community they live in?",
  "1017": "As the US becomes more diverse, are young people more inclined to vote if the ballots and guides are in various languages besides the languages we already have available?",
  "1018": "Do we need a special language to invite youth to vote?",
  "1019": "How can we educate younger folks about the value of voting?",
  "1020": "How might we educate young voters about voting and becoming engaged?",
  "1021": "How might we help the younger generation know their voice is heard in voting?",
  "1022": "How can we show the younger generation the impact of their vote?",
  "1023": "How might we make voting more of a priority to young people "
}
