kPaths = {
  "productivity": {
    "question": "How might we use the fabric display to increase productivity/efficiency in everyday life?", 
    "allwords": "increase productivity/efficiency in everyday life a shirt that you can load data into the sleeve on, in case you need notes about something later ability to write notes on clothes with touch sense", 
    "knowledgeBase": "productivity", 
    "ex1": "a shirt that you can load data into the sleeve on, in case you need notes about something later", 
    "path": "increase productivity/efficiency in everyday life", 
    "ex2": "ability to write notes on clothes with touch sense", 
    "id": "p05"
  }, 
  "visualArts": {
    "question": "How might we use the fabric display to create novel ways for visual artists to express themselves and display their work?", 
    "allwords": "create novel ways for visual artists to express themselves and display their work Use it as a canvas for art, as it reacts to touch. It would be great for making a canvas for artists that can then change based on how the artist programs it - different things appear at a different time of day, for example.", 
    "knowledgeBase": "visualArts", 
    "ex1": "Use it as a canvas for art, as it reacts to touch.", 
    "path": "create novel ways for visual artists to express themselves and display their work", 
    "ex2": "It would be great for making a canvas for artists that can then change based on how the artist programs it - different things appear at a different time of day, for example.", 
    "id": "p01"
  }, 
  "marketing": {
    "question": "How might we use the fabric display to make and display more effective advertisements in stores and in the general public?", 
    "allwords": "make and display more effective advertisements in stores and in the general public Airplane draggable banner that can display anything Personalized billboards from companies that reflect changes in weather", 
    "knowledgeBase": "marketing", 
    "ex1": "Airplane draggable banner that can display anything", 
    "path": "make and display more effective advertisements in stores and in the general public", 
    "ex2": "Personalized billboards from companies that reflect changes in weather", 
    "id": "p06"
  }, 
  "interiorDesign": {
    "question": "How might we use the fabric display to make household items/decor more visually aesthetic?", 
    "allwords": "make household items/decor more visually aesthetic A changeable room environment. Large panels of fabric hung like wallpaper on the walls of a room could create an entire environment to resemble a bamboo forest, for example, or an alpine lakeshore. The fabric could display moving wildlife such as pandas in the bamboo forest or birds on the shore of the mountain lake. The possibilities are endless! Curtains that block light but project the view outside", 
    "knowledgeBase": "interiorDesign", 
    "ex1": "A changeable room environment. Large panels of fabric hung like wallpaper on the walls of a room could create an entire environment to resemble a bamboo forest, for example, or an alpine lakeshore. The fabric could display moving wildlife such as pandas in the bamboo forest or birds on the shore of the mountain lake. The possibilities are endless!", 
    "path": "make household items/decor more visually aesthetic", 
    "ex2": "Curtains that block light but project the view outside", 
    "id": "p08"
  }, 
  "liveEntertain": {
    "question": "How might we use the fabric display to enhance live show experiences?", 
    "allwords": "enhance live show experiences back drops for theater productions. This makes scenery easy to change from scene to scene use them on a float for a parade to show whatever theme you are trying to represent during the event", 
    "knowledgeBase": "liveEntertain", 
    "ex1": "back drops for theater productions. This makes scenery easy to change from scene to scene", 
    "path": "enhance live show experiences", 
    "ex2": "use them on a float for a parade to show whatever theme you are trying to represent during the event", 
    "id": "p02"
  }, 
  "personalWellness": {
    "question": "How might we use the fabric display to make it easier / more comfortable for people to fall asleep in the bedroom?", 
    "allwords": "make it easier / more comfortable for people to fall asleep in the bedroom Mood changing bed comforter night light for kids room", 
    "knowledgeBase": "personalWellness", 
    "ex1": "Mood changing bed comforter", 
    "path": "make it easier / more comfortable for people to fall asleep in the bedroom", 
    "ex2": "night light for kids room", 
    "id": "p09"
  }, 
  "games": {
    "question": "How might we use the fabric display to make physically interactive games for the entertainment for adults and/or of children?", 
    "allwords": "make physically interactive games for the entertainment for adults and/or of children Make soft interactive baby toys that are safe for use even when parents aren't around Dance floor carpet that flashes the next foot print spot after dancer hits appropriate spot", 
    "knowledgeBase": "games", 
    "ex1": "Make soft interactive baby toys that are safe for use even when parents aren't around", 
    "path": "make physically interactive games for the entertainment for adults and/or of children", 
    "ex2": "Dance floor carpet that flashes the next foot print spot after dancer hits appropriate spot", 
    "id": "p10"
  }, 
  "safety": {
    "question": "How might we use the fabric display to make clothing/wearables that enhance people's safety in different situations, activities, and work environments?", 
    "allwords": "make clothing/wearables that enhance people's safety in different situations, activities, and work environments Emergency applications that will cause the fabric to blink bright, noticeable colors when the wearer is in distress Bike shorts that display a bright yellow line down the side. You could turn these on via wi-fi on your phone, and turn it off when you get to your destination", 
    "knowledgeBase": "safety", 
    "ex1": "Emergency applications that will cause the fabric to blink bright, noticeable colors when the wearer is in distress", 
    "path": "make clothing/wearables that enhance people's safety in different situations, activities, and work environments", 
    "ex2": "Bike shorts that display a bright yellow line down the side. You could turn these on via wi-fi on your phone, and turn it off when you get to your destination", 
    "id": "p07"
  }, 
  "education": {
    "question": "How might we use the fabric display to enhance the educational experience of students inside and outside the classroom?", 
    "allwords": "enhance the educational experience of students inside and outside the classroom It can be used in school as a way to show kids how different climates in different places might feel Interactive text books for students", 
    "knowledgeBase": "education", 
    "ex1": "It can be used in school as a way to show kids how different climates in different places might feel", 
    "path": "enhance the educational experience of students inside and outside the classroom", 
    "ex2": "Interactive text books for students", 
    "id": "p04"
  }, 
  "restaurants": {
    "question": "How might we use the fabric display to enhance the customer experience at restaurants?", 
    "allwords": "enhance the customer experience at restaurants chef coats could display food images of the menu they offer. same for the waiters at a restaurant Interactive menus at restaurants - press to learn more about an item", 
    "knowledgeBase": "restaurants", 
    "ex1": "chef coats could display food images of the menu they offer. same for the waiters at a restaurant", 
    "path": "enhance the customer experience at restaurants", 
    "ex2": "Interactive menus at restaurants - press to learn more about an item", 
    "id": "p03"
  }
}

kPathArray = [{'allwords': 'make it easier / more comfortable for people to fall asleep in the bedroom Mood changing bed comforter night light for kids room',
  'ex1': 'Mood changing bed comforter',
  'ex2': 'night light for kids room',
  'id': 'p09',
  'knowledgeBase': 'personalWellness',
  'path': 'make it easier / more comfortable for people to fall asleep in the bedroom',
  'question': 'How might we use the fabric display to make it easier / more comfortable for people to fall asleep in the bedroom?'},
 {'allwords': "make clothing/wearables that enhance people's safety in different situations, activities, and work environments Emergency applications that will cause the fabric to blink bright, noticeable colors when the wearer is in distress Bike shorts that display a bright yellow line down the side. You could turn these on via wi-fi on your phone, and turn it off when you get to your destination",
  'ex1': 'Emergency applications that will cause the fabric to blink bright, noticeable colors when the wearer is in distress',
  'ex2': 'Bike shorts that display a bright yellow line down the side. You could turn these on via wi-fi on your phone, and turn it off when you get to your destination',
  'id': 'p07',
  'knowledgeBase': 'safety',
  'path': "make clothing/wearables that enhance people's safety in different situations, activities, and work environments",
  'question': "How might we use the fabric display to make clothing/wearables that enhance people's safety in different situations, activities, and work environments?"},
 {'allwords': 'increase productivity/efficiency in everyday life a shirt that you can load data into the sleeve on, in case you need notes about something later ability to write notes on clothes with touch sense',
  'ex1': 'a shirt that you can load data into the sleeve on, in case you need notes about something later',
  'ex2': 'ability to write notes on clothes with touch sense',
  'id': 'p05',
  'knowledgeBase': 'productivity',
  'path': 'increase productivity/efficiency in everyday life',
  'question': 'How might we use the fabric display to increase productivity/efficiency in everyday life?'},
 {'allwords': "make physically interactive games for the entertainment for adults and/or of children Make soft interactive baby toys that are safe for use even when parents aren't around Dance floor carpet that flashes the next foot print spot after dancer hits appropriate spot",
  'ex1': "Make soft interactive baby toys that are safe for use even when parents aren't around",
  'ex2': 'Dance floor carpet that flashes the next foot print spot after dancer hits appropriate spot',
  'id': 'p10',
  'knowledgeBase': 'games',
  'path': 'make physically interactive games for the entertainment for adults and/or of children',
  'question': 'How might we use the fabric display to make physically interactive games for the entertainment for adults and/or of children?'},
 {'allwords': 'create novel ways for visual artists to express themselves and display their work Use it as a canvas for art, as it reacts to touch. It would be great for making a canvas for artists that can then change based on how the artist programs it - different things appear at a different time of day, for example.',
  'ex1': 'Use it as a canvas for art, as it reacts to touch.',
  'ex2': 'It would be great for making a canvas for artists that can then change based on how the artist programs it - different things appear at a different time of day, for example.',
  'id': 'p01',
  'knowledgeBase': 'visualArts',
  'path': 'create novel ways for visual artists to express themselves and display their work',
  'question': 'How might we use the fabric display to create novel ways for visual artists to express themselves and display their work?'},
 {'allwords': 'make and display more effective advertisements in stores and in the general public Airplane draggable banner that can display anything Personalized billboards from companies that reflect changes in weather',
  'ex1': 'Airplane draggable banner that can display anything',
  'ex2': 'Personalized billboards from companies that reflect changes in weather',
  'id': 'p06',
  'knowledgeBase': 'marketing',
  'path': 'make and display more effective advertisements in stores and in the general public',
  'question': 'How might we use the fabric display to make and display more effective advertisements in stores and in the general public?'},
 {'allwords': 'enhance the educational experience of students inside and outside the classroom It can be used in school as a way to show kids how different climates in different places might feel Interactive text books for students',
  'ex1': 'It can be used in school as a way to show kids how different climates in different places might feel',
  'ex2': 'Interactive text books for students',
  'id': 'p04',
  'knowledgeBase': 'education',
  'path': 'enhance the educational experience of students inside and outside the classroom',
  'question': 'How might we use the fabric display to enhance the educational experience of students inside and outside the classroom?'},
 {'allwords': 'make household items/decor more visually aesthetic A changeable room environment. Large panels of fabric hung like wallpaper on the walls of a room could create an entire environment to resemble a bamboo forest, for example, or an alpine lakeshore. The fabric could display moving wildlife such as pandas in the bamboo forest or birds on the shore of the mountain lake. The possibilities are endless! Curtains that block light but project the view outside',
  'ex1': 'A changeable room environment. Large panels of fabric hung like wallpaper on the walls of a room could create an entire environment to resemble a bamboo forest, for example, or an alpine lakeshore. The fabric could display moving wildlife such as pandas in the bamboo forest or birds on the shore of the mountain lake. The possibilities are endless!',
  'ex2': 'Curtains that block light but project the view outside',
  'id': 'p08',
  'knowledgeBase': 'interiorDesign',
  'path': 'make household items/decor more visually aesthetic',
  'question': 'How might we use the fabric display to make household items/decor more visually aesthetic?'},
 {'allwords': 'enhance live show experiences back drops for theater productions. This makes scenery easy to change from scene to scene use them on a float for a parade to show whatever theme you are trying to represent during the event',
  'ex1': 'back drops for theater productions. This makes scenery easy to change from scene to scene',
  'ex2': 'use them on a float for a parade to show whatever theme you are trying to represent during the event',
  'id': 'p02',
  'knowledgeBase': 'liveEntertain',
  'path': 'enhance live show experiences',
  'question': 'How might we use the fabric display to enhance live show experiences?'},
 {'allwords': 'enhance the customer experience at restaurants chef coats could display food images of the menu they offer. same for the waiters at a restaurant Interactive menus at restaurants - press to learn more about an item',
  'ex1': 'chef coats could display food images of the menu they offer. same for the waiters at a restaurant',
  'ex2': 'Interactive menus at restaurants - press to learn more about an item',
  'id': 'p03',
  'knowledgeBase': 'restaurants',
  'path': 'enhance the customer experience at restaurants',
  'question': 'How might we use the fabric display to enhance the customer experience at restaurants?'}]